# Generated by Django 5.2 on 2025-04-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código del producto')),
                ('category', models.CharField(max_length=50, verbose_name='Categoría')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock disponible')),
                ('unit', models.CharField(default='unidad', max_length=20, verbose_name='Unidad de medida')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está activo')),
                ('is_taxable', models.BooleanField(default=True, verbose_name='Gravado con IVA')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
        ),
    ]
